service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-mocha-plugin
  - serverless-webpack
  - serverless-aws-documentation
  - serverless-offline
  - api-gateway-stage-tag-plugin

package:
  exclude:
    - "**/node_modules/**"
  # Third party dependencies that need to be included in packaged deployable.
  # include:
  #   - "**/node_modules/uuid/**"

provider:
  name: aws
  runtime: nodejs6.10
  stackTags:
    Application: CDS-US-NonProduction-AppName
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: src/handler.lambdaHandler
    events:
      - http:
          method: get
          path: hello
